server:
  port: 9002

spring:
  application:
    name: DECRYPT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
