server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

spring.cloud.gateway:
  routes:
    - id: DECRYPT-SERVICE
      uri: lb://DECRYPT-SERVICE
      predicates:
        - Path=/decrypt/**

    - id: ENCRYPT-SERVICE
      uri: lb://ENCRYPT-SERVICE
      predicates:
        - Path=/test/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
